version: '3.8'
services:
  server:
    build:
      server/
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    depends_on:
        - postgres
    environment:
      DATABASE_URL: postgres://root:root@postgres:5432/database
  client:
    build:
      client/
    container_name: docker-next
    ports:
      - '3001:3000'
    depends_on:
      - server
  postgres:
    image: postgres:15.4-alpine
    environment:
      TZ: 'Europe/Paris'
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
volumes:
  client:
  database_data:
  server: